# Generated by Django 5.0.3 on 2024-06-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academyInstructor', '0003_course_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
