# Generated by Django 5.0.3 on 2024-06-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academyStudent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='account',
        ),
    ]
